### PR TITLE
Align default output folder with Gradle best practices

### LINKED ISSUE #754: Use plural form default output directory 'generated/sources'
Currently the plugin per default generates the generated java code into "$project/$buildDir/generated/source".
This kinda breaks Gradle best practices, please see screenshot below:

Screenshot 2024-05-02 at 21 49 26

As you can see, all other stuff in the build directory uses a plural based syntax. Even the protobuf plugin does that e.g. for "extracted-protoS" and so on. Also for that manner the generated code is not aggregated with the other generated sources in their respective  sourceSets under "generated/sourceS".

Please align the plugins output to the best practices.

Optionally:
What is the reasoning behind not having the configurable?

### PR DESCRIPTION
**Pull request by holgerstolzenberg**
Fixes #754

### CODE REVIEW

**Comment by holgerstolzenberg** [comment]
What do I have to do to get that one reviewed?

**Review by ejona86 — APPROVED** [review]

**Comment by ejona86** [comment]
Some GitHub Actions are failing. The error "exec: /nothing: not found" is suspicious and they haven't run in 6 months, so I suspect they are broken on master, best guess due to an Ubuntu upgrade. That'll need some investigation.

**Comment by ejona86** [comment]
Looks like the CI is still failing, and the CI is working fine on `master`, so the problem is this PR.

It looks like the `/nothing` is a red herring. It was just part of stderr but [was expected](https://github.com/google/protobuf-gradle-plugin/blob/ecc9b9700351694a58da083e96e2053f8d9bce1f/src/test/groovy/com/google/protobuf/gradle/ProtobufJavaPluginTest.groovy#L696). Looking higher in the log shows the error:
```
com.google.protobuf.gradle.ProtobufJavaPluginTest > test proto extraction is up-to-date for testProject when changing java sources [gradle 7.6] STANDARD_ERROR

    FAILURE: 
    Build failed with an exception.


    * Where:

    Script '/home/runner/work/protobuf-gradle-plugin/protobuf-gradle-plugin/build/tests/testProject/build_base.gradle' line: 132


    * What went wrong:

    Execution failed for task ':test'.

    > 
    assert expectedDirs == actualDirs

             |            |  |

             |            |  []

             |            false

             [/home/runner/work/protobuf-gradle-plugin/protobuf-gradle-plugin/build/tests/testProject/build/generated/source/proto/main/java]
```

I think you need to update the test projects, like:
https://github.com/google/protobuf-gradle-plugin/blob/ecc9b9700351694a58da083e96e2053f8d9bce1f/testProjectKotlinDslBase/build.gradle.kts#L126

**Comment by holgerstolzenberg** [comment]
You are totally right - the tests completely slipped my radar 🙈.

Actually searching the codebase reveals much more spots if output path assertions. I fixed them all. The problem is I cannot fully run the tests locally, I have no Android setup and other stuff is also missing. I tested the plugin manually after building it locally and it worked.

I had hopes I could just run it through the CI here - but it looks like GitHub is not kicking the build again....

**Review by ejona86 — APPROVED** [review]

**Pull request merged**
