### PR TITLE
Prepare for 0.8.7 release

### PR DESCRIPTION
**Pull request by ellisjoe**

### CODE REVIEW

**Comment by ellisjoe** [comment]
@zpencer

**Comment by ellisjoe** [comment]
as far as I can tell this is failing on artifact upload?

```
[32;1mchanges detected, packing new archive[0m
.
.
.
.
.
.
.
.
[32;1muploading archive[0m

travis_time:end:009f461a:start=1539098197015233933,finish=1539098255512872471,duration=58497638538
[0Ktravis_fold:end:cache.2
[0K
Done. Your build exited with 1.
```

**Comment by zpencer** [comment]
I think the release is something we (the maintainers) must do, because it requires having write credentials to https://plugins.gradle.org/. @zhangkun83

**Comment by zhangkun83** [comment]
Yes I will make a release. I am just wondering if we should wait for #262. @zpencer, WDYT?

**Comment by zpencer** [comment]
Let's not wait for #262 for this release

**Comment by zhangkun83** [comment]
CI is broken. I will try to fix it before making a release. (Contribution is welcome).

**Comment by marcoferrer** [comment]
Today I was able to wrap up the work for https://github.com/google/protobuf-gradle-plugin/pull/262 including tests. It still needs another review but might be ready in time for this release.

**Pull request closed without merging**
