### PR TITLE
Support extracting from '*.tgz' files

### PR DESCRIPTION
**Pull request by ellisjoe**

### CODE REVIEW

**Comment by ellisjoe** [comment]
@zhangkun83 I'm unable to tag a reviewer but was hoping you'd be able to help me find one. thanks!

**Comment by zpencer** [comment]
Thanks for your PR!

**Comment by ellisjoe** [comment]
awesome thanks @zpencer! not sure what your release cycle is but I would love to see a release with this change

**Comment by zpencer** [comment]
@zhangkun83 can you run a release?

**Comment by zhangkun83** [comment]
0.8.7 is out!

**Pull request merged**
