### PR TITLE
Added support to compile proto files individually

### PR DESCRIPTION
**Pull request by BWMuller**

### CODE REVIEW

**Comment by voidzcy** [comment]
What's the reason to compile each proto individually?

**Comment by BWMuller** [comment]
I have a case where I've had proto files from a packageA that directly without path imports it's other proto files. By itself this compiles fine. However a second packageB was introduced that imports packageA in its profo file. Due to the size and dependancy A could not be changed to also use packaged imports since it had the same proto file names as other packages on the server. Which results in a shadowed exception when compiled as a batch. 

Thus this Pr which allows for proto files to be compiled individually instead of as a single unit. 

The code could always be improved to change from a true/false bool to an enum that is (Single, Package, File) scoped for its compiles, depending on what is needed by the developers

**Comment by BWMuller** [comment]
Example structure would be
```
A
  -> message.proto (includes user.proto)
  -> user.proto

B
  -> message.proto (includes A/message.proto)

C
  -> message.proto (includes account.proto)
  -> account.proto
```

**Comment by voidzcy** [comment]
> Example structure would be
> 
> ```
> A
>   -> message.proto (includes user.proto)
>   -> user.proto
> 
> B
>   -> message.proto (includes A/message.proto)
> 
> C
>   -> message.proto (includes account.proto)
>   -> account.proto
> ```

What's the problem for compiling this example? Given that B's `message.proto` contains `import "A/message.proto"`.

**Comment by BWMuller** [comment]
The gradle plugin allows for specific imports (srcDir as can be defined in the sourceSet). Namely an option is the contents of each folder individually or the parent folder thus including all three sub folders. This can also be adjusted with the excludes to ignore others.

##### Attempt A
When including only A directly it compiles fine. As soon as B is added directly due to the single compile command. It will result in a `Input is shadowed` exception thrown by the protoc compiler. 

##### Attempt B
Just including the entire directory means that A cannot compile since the imports cannot be found since all its imported folders are under `A/..` which aren't imported as such (Cannot change this unfortunately). B can compile fine since now it knows where the `A/..` imports are located

##### Attempt C
Using a hybrid of the two by including A directly and the parent directory as well and excluding the subfolder A from compiling (again) would result in a success. But fails on imports as well due to everything being compiled as one. Don't have the exact error now but can look it up again if needed.

##### Current Solution
Thus the single file flag that I added. This allows each proto to have its own protoc compile command run, creating a clean separation between the different includes used allowing for a successful compile

While this could normally be solved by fixing the file names to not overlap and changing the imports to import everything correctly, it would not work if there is no control over the proto structure. In the event (which it partly is for me) where the proto structure is maintained and managed by an external that won't change the structure, the option for single file or folder compile becomes significantly more important

**Comment by zhangkun83** [comment]
To help us better understand your use case, could you provide a minimal example project that demonstrate your project structure and reproduces the issue?

**Pull request closed without merging**
