### PR TITLE
for generateProto, delete the output directory before calling protoc

### PR DESCRIPTION
**Pull request by devinrsmith**
Fix for #331 / #332

### CODE REVIEW

**Comment by devinrsmith** [comment]
@googlebot I signed it!

**Comment by joschi** [comment]
I've been running into the same problem and worked around it as described in https://github.com/google/protobuf-gradle-plugin/issues/331#issuecomment-543333726.

Any chance of getting this PR merged?

**Comment by voidzcy** [comment]
> I've been running into the same problem and worked around it as described in [#331 (comment)](https://github.com/google/protobuf-gradle-plugin/issues/331#issuecomment-543333726).
> 
> Any chance of getting this PR merged?

We can't get this merged as long as people are pointing `generatedFilesBaseDir` to their custom directory for generated files. People used to use it for putting generate files together with other files. We cannot just wipe the directory (see #332).

For general cases, you should at most need a clean build and that will delete unnecessary files after you proto definition changes.

**Comment by mattwelke** [comment]
> For general cases, you should at most need a clean build and that will delete unnecessary files after you proto definition changes.

So the solution here would be to do a `./gradlew clean build` for example? The clean deletes the old generated Java source code, and the build creates new code?

**Comment by ejona86** [comment]
#636 was merged in favor of this one. This has been a long-time pain, so I appreciate the effort to get it fixed.

**Pull request closed without merging**
