### PR TITLE
Fix input and output annotations

### PR DESCRIPTION
**Pull request by zhangkun83**
With Gradle 6.0 we are starting to enforce annotations on all task getters. Non ad-hoc tasks should use annotations in place of the `Task.getInputs()` and `getOutputs()` APIs. Due to these changes with Gradle 6.0 the applying the Protobuf plugin results in the following deprecation warnings being displayed:

```text
   > Warning: Type 'GenerateProtoTask': property 'buildType' is not annotated with an input or output annotation.
   > Warning: Type 'GenerateProtoTask': property 'builtins' is not annotated with an input or output annotation.
   > Warning: Type 'GenerateProtoTask': property 'descriptorPath' is not annotated with an input or output annotation.
   > Warning: Type 'GenerateProtoTask': property 'descriptorSetOptions' is not annotated with an input or output annotation.
   > Warning: Type 'GenerateProtoTask': property 'fileResolver' is not annotated with an input or output annotation.
   > Warning: Type 'GenerateProtoTask': property 'flavors' is not annotated with an input or output annotation.
   > Warning: Type 'GenerateProtoTask': property 'generateDescriptorSet' is not annotated with an input or output annotation.
   > Warning: Type 'GenerateProtoTask': property 'isTest' is not annotated with an input or output annotation.
   > Warning: Type 'GenerateProtoTask': property 'isTestVariant' is not annotated with an input or output annotation.
   > Warning: Type 'GenerateProtoTask': property 'outputSourceDirectorySet' is not annotated with an input or output annotation.
   > Warning: Type 'GenerateProtoTask': property 'plugins' is not annotated with an input or output annotation.
   > Warning: Type 'GenerateProtoTask': property 'sourceFiles' is not annotated with an input or output annotation.
   > Warning: Type 'GenerateProtoTask': property 'sourceSet' is not annotated with an input or output annotation.
   > Warning: Type 'GenerateProtoTask': property 'variant' is not annotated with an input or output annotation.
   > Warning: Type 'ProtobufExtract': property 'destDir' is not annotated with an input or output annotation.
   > Warning: Type 'ProtobufExtract': property 'isTest' is not annotated with an input or output annotation.
```

This PR fixes the problems and the warnings are removed. This is based on #351 by @lptr

### CODE REVIEW

**Comment by lptr** [comment]
Thanks for the quick reply @zhangkun83! The changes look good to me, though maybe replace `ForUpToDateCheck` with `ForCaching`, as it also influences caching. But that's a minor detail. Let's merge this!

**Comment by zhangkun83** [comment]
@lptr, could you leave a comment per what googlebot said?

**Comment by lptr** [comment]
@googlebot I consent.

**Comment by lptr** [comment]
Thanks @zhangkun83! Do you know when this is going to be released?

**Comment by zhangkun83** [comment]
@voidzcy we should probably make a new release after #366 is merged. I will let you do the next release to make sure the process works for you.

**Pull request merged**
