### PR TITLE
Support packaging and extracting protos in Android aar

### LINKED ISSUE #435: protobuf packaging doesnt retain directory structure in Android aar libraries
Generating a protobuf library on android doesn't retain the directory structure from the base "src/main/proto" folder.

e.g. A folder structure of:
```
src/main/proto
├── a.proto
├── firstfolder
│   └── b.proto
└── secondfolder
    └── c.proto
```

will package all corresponding .protobuf files into the root directory of the packaged .aar file instead of in the corresponding folders (firstfolder and secondfolder).

This means that applications consuming the protobuf library and trying to import the `b.proto` file using
`import "firstfolder/b.proto"` will fail.

I assume the inclusion of proto files is here: https://github.com/google/protobuf-gradle-plugin/blob/master/src/main/groovy/com/google/protobuf/gradle/ProtobufPlugin.groovy#L273 or https://github.com/google/protobuf-gradle-plugin/blob/master/src/main/groovy/com/google/protobuf/gradle/ProtobufPlugin.groovy#L293. But I'm not quite sure why the directory structure is not retained.

### PR DESCRIPTION
**Pull request by voidzcy**
Adds support for packaging proto files into the aar for Android library projects and extracting proto files from aar dependencies.

-----------
The CI failure should be fixed by #441. 

Fixes #435

### CODE REVIEW

**Comment by voidzcy** [comment]
I am highly suspecting this chunk of code is redundant and can be deleted:
https://github.com/google/protobuf-gradle-plugin/blob/7f964837a825af2a3e9c32d61889b66aa98b22a1/src/main/groovy/com/google/protobuf/gradle/ProtobufPlugin.groovy#L403-L423

**Review by ejona86 — APPROVED** [review]
How hard would it be to have a test?

**Comment by voidzcy** [comment]
> How hard would it be to have a test?

Yep, that's something still under consideration.

**Comment by voidzcy** [comment]
I found a solution to workaround the issue of using project dependencies in tests (yes, the existing [Java's `testProjectDependentApp`](https://github.com/google/protobuf-gradle-plugin/blob/529103114d9eb1d13e7622b38dda0bc8bbfa58bf/src/test/groovy/com/google/protobuf/gradle/ProtobufJavaPluginTest.groovy#L284-L313) is not working the intended way as well):

https://github.com/google/protobuf-gradle-plugin/blob/529103114d9eb1d13e7622b38dda0bc8bbfa58bf/testProjectDependentApp/build.gradle#L18

to

```
implementation(project(':testProjectJavaLibrary')) {
        attributes {
            attribute(LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE,
                    project.getObjects().named(LibraryElements, LibraryElements.JAR))
        }
 }
```

which [mutates the attributes](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ModuleDependency.html#attributes-org.gradle.api.Action-) of the project dependency and changes its `libraryelements` attribute for variant selection (some docs [here](https://docs.gradle.org/current/userguide/variant_model.html) and [here](https://docs.gradle.org/current/userguide/variant_attributes.html)). Therefore, we can force it to pull in the Jar instead of just classes (`java-library`'s default) and resources (what our internal `compileProtoPath` enforces).

By turning on the log, you can see the difference for `testProjectDependentApp:extractIncludeProto` task:

```
Extracting protos from *********************/protobuf-gradle-plugin/build/tests/testProjectDependentAppMain/testProjectJavaLibrary/build/resources/main to /Users/chengyuanzhang/Documents/grpc_java/protobuf-gradle-plugin/build/tests/testProjectDependentAppMain/testProjectDependentApp/build/extracted-include-protos/main
Extracting protos from *********************/protobuf-gradle-plugin/build/tests/testProjectDependentAppMain/testProjectJavaLibrary/build/classes/java/main to /Users/chengyuanzhang/Documents/grpc_java/protobuf-gradle-plugin/build/tests/testProjectDependentAppMain/testProjectDependentApp/build/extracted-include-protos/main
```

vs

```
Extracting protos from ***************/protobuf-gradle-plugin/build/tests/testProjectDependentAppMain/testProjectJavaLibrary/build/libs/testProjectJavaLibrary.jar to /Users/chengyuanzhang/Documents/grpc_java/protobuf-gradle-plugin/build/tests/testProjectDependentAppMain/testProjectDependentApp/build/extracted-include-protos/main
```

**Pull request merged**
