### PR TITLE
Provide optional system property `protocExecutable` to override protoc path

### PR DESCRIPTION
**Pull request by sundbry**
Issue #426

### CODE REVIEW

**Comment by sundbry** [comment]
@googlebot I signed it!

**Comment by voidzcy** [comment]
This doesn't seem to be _Gradle-like_. It is weird to see "use this executable" in the buildscript while something else is actually used.

However, you could add such a system property to your own project (or a tasks that reads it) and feed the result to `protoc.path` of this plugin. Then your users can use the property to specify the path to binary in their local filesystem.

**Comment by ejona86** [comment]
Note that I'd quickly agree that manually plumbing the `protoc.path` is annoying. But that seems to be the status-quo for many fields that are dependent on the environment. Gradle is oriented toward a configuration that works the same everywhere. On the flip-side, that does decrease the amount of "funny business" that can happen when you're trying to understand a script.

**Comment by sundbry** [comment]
@voidzcy @ejona86 I am coming at this from a package maintainer's perspective (not an application developer). The embedded protoc is not usable for reasons mentioned in the linked issue. Ironically, a primary design of both Nix and Guix is to achieve the same thing, byte-for-byte reproducible builds and environments. Of course we have the capability to patch-in `protoc { path '....' }` into build.gradle in the package build scripts, but that is significantly more involved to maintain patch files. The 'maven' way to approach this is with toolchains.xml, which can specify the path to native toolchains (such as gcc, protoc, etc).

In dealing with native code/tools, gradle is somewhat out of its design space although I am sure some Android developers would rebut that. In the official `grpc-java` package a combination of both approaches is used, the build.gradle allows `gradle build -Pprotoc=/my/protoc` using the `protoc` property to specify a system protoc, which gets shimmed into `protoc { path '....' }' as you mentioned.

**Comment by ejona86** [comment]
> I am coming at this from a package maintainer's perspective (not an application developer)

I understand. But this "configure inside of gradle, not outside" is not new. For example, to cross-compile a C++ component you have to have specific logic in the gradle file. For specifying username/password to use for uploading packages, gradle file. It isn't designed to have a separate package maintainer, like autotools or the like.

Gradle puts the application developer in control of the build. This can be considered a feature, as it means the application developer knows exactly what will happen during the build. But it does have the downfall that it works less well when the app developer and package developer are different entities.

From what we've seen, "the Gradle way" is to do like grpc-java and put specialized code in the gradle file to allow `-Pprotoc=/my/protoc`. (This shouldn't be surprising, as both of us are also grpc-java maintainers; I actually approved [that change](https://github.com/grpc/grpc-java/pull/422).) This sort of approach is reasonably common in the gradle documentation.

I'd actually be quite happy to hear of commonly-used counter examples, for something to mirror. And I'll also totally admit that we lack knowledge of many aspects of Gradle. But I want to work with the system instead of against it. Also, I don't want to override the user (which specified something specific in the gradle.build); if this was a _default_ it would be easier to justify.

I would agree that this is a bit different that many other cases with Gradle, as it is platform-specific. Normally the dependencies can be used on any environment. But it is similar to C++ compilation, which has been quite annoying in this regard and I'm not sure where it will land.

**Comment by voidzcy** [comment]
Closing. As in the discussion, this is more appropriate to be done in user's own project instead of built into this plugin.

**Pull request closed without merging**
