### PR TITLE
Restrict getOutputSourceDirectorySet() to directories only

### PR DESCRIPTION
**Pull request by cilki**
#480 allows `outputPath` to be a zip/jar file, but it's not excluded from the `SourceDirectorySet` in that case. Therefore, when the source set gets evaluated, it leads to this exception in Gradle 7.2:

```
Caused by: org.gradle.api.InvalidUserDataException: Source directory '<redacted>/build/generated-proto/main/cpp.zip' is not a directory.
	at org.gradle.api.internal.file.DefaultSourceDirectorySet.getSourceTrees(DefaultSourceDirectorySet.java:273)
	at org.gradle.api.internal.file.DefaultSourceDirectorySet.getSrcDirTrees(DefaultSourceDirectorySet.java:256)
	at org.gradle.api.internal.file.DefaultSourceDirectorySet.getSrcDirs(DefaultSourceDirectorySet.java:114)
	at jdk.internal.reflect.GeneratedMethodAccessor2253.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.google.protobuf.gradle.ProtobufPlugin$_addSourcesToIde_closure31.doCall(ProtobufPlugin.groovy:554)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.google.protobuf.gradle.ProtobufPlugin.addSourcesToIde(ProtobufPlugin.groovy:553)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.google.protobuf.gradle.ProtobufPlugin$_doApply_closure5.doCall(ProtobufPlugin.groovy:159)
...
```

The fix is to just ignore files when creating the source directory for generated output.

### CODE REVIEW

**Comment by cilki** [comment]
@googlebot I signed it!

**Review by ejona86 — APPROVED** [review]
I wonder if it was a mistake to do #480, like it was a mistake to have generatedFilesDir. But it looks like this is just for the IDE, and yeah, that shouldn't break.

**Comment by cilki** [comment]
I like the idea of outputting directly to a Zip file, but it seems strange to do it with this method: https://github.com/google/protobuf-gradle-plugin/blob/8a35d4648db0da0dbfd203e1b4be324e941b622e/src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy#L509

Although it does work perfectly after the change in this PR.

**Comment by ejona86** [comment]
Arg. We're bitten by the travis-ci.org migration. I'm a bit surprised that it only now started failing, but it was still working in August, even though it is claimed to be shut off in June.

**Comment by voidzcy** [comment]
> I wonder if it was a mistake to do #480, like it was a mistake to have generatedFilesDir. But it looks like this is just for the IDE, and yeah, that shouldn't break.

It is a bit awkward to support such a usage, as packaging generated code into JAR/ZIP doesn't seem to be something that should/can be done together with source compilation (the primary goal of this plugin is to automate compilation). It would be best if users do this by themselves separately.

Many users like in #478, they use this plugin simply as a management tool for proto and generated code (mostly for languages other than Java family). As supporting this doesn't do harm to existing functionalities, I accepted it.

**Review by voidzcy — APPROVED** [review]

**Comment by voidzcy** [comment]
@ejona86 Could you help with fixing Travis for this repo?

**Comment by ejona86** [comment]
@voidzcy, I can't fix it right now. Instead of migrating to travis-ci.com we've generally been migrating off of travis, like to github actions. That isn't that hard, but isn't "do it in 5 minutes."

**Comment by ejona86** [comment]
Sent out #525 for CI migration.

**Comment by cilki** [comment]
Anything else I can do to push this one through?

**Comment by ejona86** [comment]
@cilki, there were test failures. The failures are in ProtobufJavaPluginTest, so shouldn't be too hard for you to reproduce and take a look. If the failure doesn't make much sense I can help take a look, but it doesn't seem like a flake at first glance.

**Comment by cilki** [comment]
@ejona86 I'll give it a go. The tests were failing for me before I made any changes, so I'll investigate that first.

**Comment by ejona86** [comment]
@cilki, the Android tests and such can be more annoying, but I thought that one failing test should be easier. If no progress, just report back.

**Comment by cilki** [comment]
Indeed some of the test failures were my fault for using Java 11 instead of Java 8. I fixed the actual issue, but rebased in the meantime which seems to have messed some things up. I'll make a new PR.

**Pull request closed without merging**
