### PR TITLE
Pass protoc options.

### LINKED ISSUE #6: Support protoc plugin options
Plugins sometimes support parameters by passing semicolon-delimited options before the output file name of the out paramater passed to protoc.

Nano for Java [uses this heavily](https://github.com/google/protobuf/tree/master/javanano#to-use-nano-protobufs-outside-of-android-repo). To use Nano with gRPC you also need to add [nano=true](https://github.com/grpc/grpc-java/tree/master/compiler).

We need a way to provide such options.

### PR DESCRIPTION
**Pull request by zhangkun83**
Resolves #6

@ejona86 @madongfly please review

- Options are per-sourceSet, so you can configure a sourceSet to generate
normal Java, and another sourceSet to generate nano.
- ``protobufCodeGenPlugins`` and ``protobufNativeCodeGenPluginDeps`` will no longer apply all plugins automatically. Plugins need to be configured in the ``sourceSets`` explicitly.

Example:
```
sourceSets {
  main {
    proto {
      // Configure built-in outputs.
      builtins {
        // 'java' is added by default. If you don't want additional options,
        // you don't need to write this block.
        java {
          // Options added to --java_out
          option 'option1=true'
        }
      }
    }
  }
  nano {
    proto {
      // Configure built-in outputs. Default is 'java'. Here we only build javanano.
      builtins {
        remove java
        javanano {
          // Options added to --javanano_out
          option 'java_multiple_files=true'
          option 'option2=false'
        }
      }
      // Apply the 'grpc' plugin
      plugins {
        grpc {
          // Options added to --grpc_out
          option 'nano=true'
          option 'option2=false'
        }
        // Apply the 'xrpc' plugin without options
        xrpc { }
      }
    }
  }
}
```

### CODE REVIEW

**Comment by zhangkun83** [comment]
@madongfly I have pushed it to the snapshot repository. You should be able to try it with the following configuration:

```
buildscript {                                                                                            
  repositories {
    maven {                                                                                              
      url 'https://oss.sonatype.org/content/repositories/snapshots/'                                     
    }                                                               
  }                                                                                                      
  dependencies {                                                                                         
    classpath "com.google.protobuf:protobuf-gradle-plugin:0.3.2-SNAPSHOT"                        
  }                                                                                                      
}
```

**Comment by ejona86** [comment]
Should the syntax be more like:
```
plugins {
  grpc {
    // Options added to --grpc_out
    option 'nano=true'
    option 'option2=false'
  }
}
```

That would remove the unexpected comma.

Should the options be a map where the value is optional (it would be `null`)? The use of `=` is [part of the parser](https://github.com/google/protobuf/blob/61477681710871dab2a5832d0d6324aa9b7d7867/src/google/protobuf/compiler/code_generator.cc#L69).

For a bit I wondered if java and javanano should be treated as plugins, since the only difference with them is they are built-in, which isn't even special if other plugins are in PATH. But I guess we would always want to specify the path to a plugin, unless it is one of the built-in ones, since we want to guarantee what version is being used.

**Comment by zhangkun83** [comment]
I have implemented the options in the more fashionable container style. Still imperfect -- when there is no options, you still need the braces, otherwise the item won't be added.

> Should the options be a map where the value is optional (it would be null)? The use of = is part of the parser.

I doubt doing so gives us any good. Since we don't validate the option strings anyway, why should we care how protoc parses them? Using a map and allowing null values would bring us unnecessary complexity.

> For a bit I wondered if java and javanano should be treated as plugins, since the only difference with them is they are built-in, which isn't even special if other plugins are in PATH. But I guess we would always want to specify the path to a plugin, unless it is one of the built-in ones, since we want to guarantee what version is being used.

I like this idea because of its flexibility and consistency with plugins. I would separate from the plugins and put them in ``builtins`` to prevent confusion. I put ``java`` by default, but this means if you only need ``javanano``, you have to remove ``java`` explicitly, which doesn't look very nice. Please take a look at commit 8a411a3.

**Comment by ejona86** [comment]
> Still imperfect -- when there is no options, you still need the braces, otherwise the item won't be added.

That's fine. I'

**Comment by ejona86** [comment]
> I would separate from the plugins and put them in builtins to prevent confusion.

That sounds good.

> I put java by default, but this means if you only need javanano, you have to remove java explicitly, which doesn't look very nice.

Yeah, I had expected that issue... I don't see any tweaks we could do to make it any nicer.

**Pull request merged**
